name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Setup .NET 8
        uses: actions/setup-dotnet@6db8d8351a62dab7d77a5f9413b4d8de0e37f374  # v4.0.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore AppName.sln

      - name: Build
        run: dotnet build AppName.sln -c Release --no-restore

      - name: Test
        run: dotnet test tests/AppName.Service.Tests -c Release --no-build -v minimal
